import React from 'react';

import { View, Text, StyleSheet, FlatList, TouchableOpacity, Alert, Platform, Linking } from 'react-native';
import { useStore, CartItem } from '../store/useStore';
import { generatePDF as convertToPDF } from 'react-native-html-to-pdf';
import Share from 'react-native-share';
import { theme } from '../theme';
import Icon from 'react-native-vector-icons/MaterialIcons';

const CartScreen = () => {
    const { cart, removeFromCart } = useStore();

    const generatePDF = async () => {
        if (cart.length === 0) {
            Alert.alert('Empty Cart', 'Add items first');
            return;
        }

        try {
            // Generate HTML Table
            let rows = cart.map((item, index) => `
                <tr style="background-color: ${index % 2 === 0 ? '#fff' : '#f9f9f9'};">
                    <td style="padding: 12px; border: 1px solid #ddd;">${item.product.productName}</td>
                    <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold;">${item.selection}</td>
                </tr>
            `).join('');

            const html = `
                <html>
                <head>
                    <style>
                        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
                        h1 { text-align: center; color: #2c3e50; margin-bottom: 30px; }
                        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                        th { background-color: #2c3e50; color: white; padding: 12px; text-align: left; }
                        .footer { margin-top: 30px; text-align: right; font-size: 12px; color: #888; }
                    </style>
                </head>
                <body>
                    <h1>Order Summary</h1>
                    <table>
                        <tr>
                            <th>Product Name</th>
                            <th>Quantity / Note</th>
                        </tr>
                        ${rows}
                    </table>
                    <div class="footer">
                        Generated by e-sbe App on ${new Date().getDate()}/${new Date().getMonth() + 1}/${new Date().getFullYear()}
                    </div>
                </body>
                </html>
            `;

            const options = {
                html,
                fileName: `Order_${Date.now()}`,
                directory: 'Documents',
            };

            const file = await convertToPDF(options);

            console.log('PDF generated at:', file.filePath);

            const shareOptions = {
                title: 'Share Order (PDF)',
                url: `file://${file.filePath}`,
                type: 'application/pdf',
                message: 'Here is my order summary (PDF)',
                social: Share.Social.WHATSAPP,
                whatsAppNumber: '', // Provide empty if general share
                failOnCancel: false,
            } as any;

            try {
                await Share.shareSingle(shareOptions);
            } catch (err) {
                console.log("WhatsApp specific share failed, falling back to general share", err);
                // Fallback to general open
                await Share.open({
                    url: `file://${file.filePath}`,
                    type: 'application/pdf',
                    message: 'Here is my order summary (PDF)',
                    title: 'Send Order'
                });
            }

        } catch (error) {
            console.error(error);
            Alert.alert('Error', 'Failed to generate or share PDF. Please check permissions.');
        }
    };

    const shareText = async () => {
        if (cart.length === 0) {
            Alert.alert('Empty Cart', 'Add items first');
            return;
        }

        let message = "*Order Summary*\n------------------\n\n";
        cart.forEach(item => {
            message += `*${item.product.productName}*\n`;
            message += `> ${item.selection}\n\n`;
        });
        message += `_Generated on ${new Date().getDate()}/${new Date().getMonth() + 1}/${new Date().getFullYear()}_`;

        // Strategy 1: Attempt Linking (most reliable for just text)
        const url = `whatsapp://send?text=${encodeURIComponent(message)}`;

        try {
            const supported = await Linking.canOpenURL(url);
            if (supported) {
                await Linking.openURL(url);
            } else {
                // Fallback to React Native Share if WhatsApp not installed/detected
                await Share.open({
                    message: message,
                    title: 'Order Summary'
                });
            }
        } catch (err) {
            console.error('Share Error:', err);
            // Last resort
            await Share.open({
                message: message,
                title: 'Order Summary'
            });
        }
    };

    const renderItem = ({ item }: { item: CartItem }) => (
        <View style={styles.item}>
            <View style={{ flex: 1 }}>
                <Text style={styles.name}>{item.product.productName}</Text>
                <Text style={[styles.sel, item.selection.startsWith('Note:') ? { color: '#e67e22', fontStyle: 'italic' } : {}]}>
                    {item.selection}
                </Text>
            </View>
            <TouchableOpacity onPress={() => removeFromCart(item.id)} style={styles.removeBtn}>
                <Icon name="delete-outline" size={24} color="#e74c3c" />
            </TouchableOpacity>
        </View>
    );

    return (
        <View style={styles.container}>
            <View style={styles.header}>
                <Text style={styles.headerTitle}>Your Cart</Text>
                <Text style={styles.headerSubtitle}>{cart.length} Items</Text>
            </View>

            <FlatList
                data={cart}
                keyExtractor={i => i.id}
                renderItem={renderItem}
                contentContainerStyle={styles.listContent}
                ListEmptyComponent={
                    <View style={styles.emptyContainer}>
                        <Icon name="remove-shopping-cart" size={64} color="#ccc" />
                        <Text style={styles.emptyText}>Your cart is empty</Text>
                    </View>
                }
            />

            <View style={styles.footer}>
                <TouchableOpacity style={[styles.shareBtn, { backgroundColor: theme.colors.primary }]} onPress={generatePDF}>
                    <Icon name="picture-as-pdf" size={20} color="#fff" style={{ marginRight: 10 }} />
                    <Text style={styles.shareText}>Share PDF</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[styles.shareBtn, { backgroundColor: '#25D366' }]} onPress={shareText}>
                    <Icon name="chat" size={20} color="#fff" style={{ marginRight: 10 }} />
                    <Text style={styles.shareText}>WhatsApp Text</Text>
                </TouchableOpacity>
            </View>
        </View>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f5f7fa' },
    header: {
        padding: 20,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'baseline'
    },
    headerTitle: { fontSize: 24, fontWeight: '800', color: theme.colors.primary },
    headerSubtitle: { fontSize: 16, color: '#888', fontWeight: '500' },
    listContent: { padding: 15 },
    item: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 16,
        marginBottom: 12,
        borderRadius: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2
    },
    name: { fontSize: 15, color: '#2d3436', fontWeight: '700', marginBottom: 4 },
    sel: { fontSize: 13, color: theme.colors.primary, fontWeight: '500' },
    removeBtn: { padding: 8 },
    emptyContainer: { alignItems: 'center', justifyContent: 'center', marginTop: 100 },
    emptyText: { marginTop: 20, fontSize: 18, color: '#999' },
    footer: {
        padding: 20,
        backgroundColor: '#fff',
        elevation: 20, // High elevation for shadow
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        gap: 12
    },
    shareBtn: {
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        elevation: 3
    },
    shareText: { color: '#fff', fontWeight: 'bold', fontSize: 16 }
});

export default CartScreen;
